apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfs-hello-kubernetes-prod-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: prod
    repoURL: "https://github.com/maaanish/hello-kubernetes-prod-config"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-app-dev1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  project: default
