apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-app
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: 'https://kubernetes.default.svc'
  source:
    path: production/
    repoURL: 'https://github.com/alaghusundhar/sundar-jenkins.git'
    targetRevision: HEAD
  project: default